name: run-concerts-me

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Write Google Service Account file
        run: |
          echo "$GOOGLE_SERVICE_CREDS" > service_account.json

      - name: Write config.json
        run: |
          echo "$CONFIG_JSON" > config.json

      - name: Run python main.py
        env:
          GOOGLE_SERVICE_CREDS: ${{ secrets.GOOGLE_SERVICE_CREDS }}
          CONFIG_JSON: ${{ secrets.CONFIG_JSON }}
        run: |
          python main.py
